using Content.Client.UserInterface.Controls;
using Content.Shared._Grosse.Pvp.UI;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Grosse.Pvp.UI;

[GenerateTypedNameReferences]
public sealed partial class PvpClassSelectMenu : FancyWindow
{
    public event Action<string>? ClassPicked;

    public PvpClassSelectMenu()
    {
        RobustXamlLoader.Load(this);
    }

    public void Update(PvpClassSelectEuiState state)
    {
        TicketsLabel.Visible = state.ShowTickets;
        TicketsLabel.Text = state.ShowTickets
            ? Loc.GetString("pvp-class-select-tickets", ("tickets", state.Tickets))
            : string.Empty;
        ClassList.RemoveAllChildren();

        foreach (var cls in state.Classes)
        {
            var id = cls.Id;
            var label = state.ShowClassCost
                ? $"{cls.Name}  ({Loc.GetString("pvp-lobby-cost", ("cost", cls.Cost))})"
                : cls.Name;
            var button = new Button
            {
                Text = label,
                ToolTip = cls.Description,
                Disabled = !cls.Affordable || !cls.Available,
                ToggleMode = true,
                Pressed = state.SelectedClass == id,
                HorizontalExpand = true,
            };
            if (!cls.Available)
                button.ToolTip = Loc.GetString("pvp-lobby-class-full");
            button.OnPressed += _ => ClassPicked?.Invoke(id);
            ClassList.AddChild(button);
        }
    }
}
