using Content.Shared._Grosse.Pvp;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Grosse.Pvp.UI;

[GenerateTypedNameReferences]
public sealed partial class PvpLoadoutPanel : Robust.Client.UserInterface.Control
{
    public event Action<bool, PvpTeam?, string?>? LoadoutSelected;

    private PvpTeam? _team;
    private string? _classId;
    private bool _random;
    private bool _showClassCost;
    private Dictionary<string, int> _classCounts = new();
    private List<PvpClassInfo> _attackersClasses = new();
    private List<PvpClassInfo> _defendersClasses = new();

    public PvpLoadoutPanel()
    {
        RobustXamlLoader.Load(this);

        AttackersButton.OnPressed += _ => SelectTeam(PvpTeam.Attackers);
        DefendersButton.OnPressed += _ => SelectTeam(PvpTeam.Defenders);
        RandomButton.OnPressed += _ => SelectRandom();
    }

    public void SetVisibleEnabled(bool enabled)
    {
        Contents.Visible = enabled;
        Visible = enabled;
    }

    public void UpdateState(PvpLobbyStateEvent state)
    {
        SetVisibleEnabled(state.Enabled);
        if (!state.Enabled)
            return;

        if (!string.IsNullOrEmpty(state.Header))
            Header.Text = state.Header;

        TeamCounts.Text = Loc.GetString("pvp-team-counts",
            ("attackersName", state.AttackersName),
            ("defendersName", state.DefendersName),
            ("attackers", state.AttackersCount),
            ("defenders", state.DefendersCount));

        AttackersButton.Text = state.AttackersName;
        DefendersButton.Text = state.DefendersName;

        _random = state.RandomSelected;
        _team = state.SelectedTeam;
        _classId = state.SelectedClass;
        _showClassCost = state.ShowClassCost;
        _classCounts = new Dictionary<string, int>(state.ClassCounts);
        _attackersClasses = state.AttackersClasses;
        _defendersClasses = state.DefendersClasses;

        AttackersButton.Pressed = !_random && _team == PvpTeam.Attackers;
        DefendersButton.Pressed = !_random && _team == PvpTeam.Defenders;
        RandomButton.Pressed = _random;

        StatusLabel.Text = _random
            ? Loc.GetString("pvp-lobby-selected-random")
            : state.CanReady
                ? string.Empty
                : Loc.GetString("pvp-lobby-ready-hint");

        RebuildClasses();
    }

    private void SelectTeam(PvpTeam team)
    {
        _random = false;
        _team = team;
        _classId = null;
        RebuildClasses();
        LoadoutSelected?.Invoke(false, team, null);
    }

    private void SelectRandom()
    {
        _random = true;
        _team = null;
        _classId = null;
        RebuildClasses();
        LoadoutSelected?.Invoke(true, null, null);
    }

    private void SelectClass(string id)
    {
        if (_team == null)
            return;

        _random = false;
        _classId = id;
        LoadoutSelected?.Invoke(false, _team, id);
    }

    private void RebuildClasses()
    {
        ClassList.RemoveAllChildren();
        if (_random || _team == null)
            return;

        var classes = _team == PvpTeam.Attackers ? _attackersClasses : _defendersClasses;
        foreach (var proto in classes)
        {
            var id = proto.Id;
            var available = IsClassAvailable(id, proto.MaxCount);
            var label = _showClassCost
                ? $"{proto.Name}  ({Loc.GetString("pvp-lobby-cost", ("cost", proto.Cost))})"
                : proto.Name;
            var button = new Button
            {
                Text = label,
                ToolTip = available ? proto.Description : Loc.GetString("pvp-lobby-class-full"),
                ToggleMode = true,
                Pressed = _classId == id,
                Disabled = !available,
                HorizontalExpand = true,
            };
            button.OnPressed += _ => SelectClass(id);
            ClassList.AddChild(button);
        }
    }

    private bool IsClassAvailable(string id, int maxCount)
    {
        if (maxCount <= 0)
            return true;

        if (_classId == id)
            return true;

        return _classCounts.GetValueOrDefault(id) < maxCount;
    }
}
