using Content.Client.Message;
using Content.Shared._Grosse.Assault;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;

namespace Content.Client._Grosse.Assault.UI;

[GenerateTypedNameReferences]
public sealed partial class AssaultHudControl : PanelContainer
{
    [Dependency] private IGameTiming _timing = default!;
    [Dependency] private IPrototypeManager _proto = default!;

    private AssaultHudUpdateEvent? _state;

    public AssaultHudControl()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        MouseFilter = MouseFilterMode.Ignore;
    }

    public void Update(AssaultHudUpdateEvent state)
    {
        _state = state;
        Visible = state.Enabled;
        Refresh();
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        if (Visible)
            Refresh();
    }

    private void Refresh()
    {
        if (_state == null || !_state.Enabled)
        {
            Visible = false;
            return;
        }

        var phase = _state.Phase switch
        {
            AssaultPhase.Prep => Loc.GetString("assault-hud-phase-prep", ("time", FormatTime(_state.PhaseEndsAt))),
            AssaultPhase.Intermission => Loc.GetString("assault-hud-phase-intermission", ("time", FormatTime(_state.PhaseEndsAt))),
            AssaultPhase.Ended => Loc.GetString("assault-hud-phase-ended"),
            _ => Loc.GetString("assault-hud-phase-attack"),
        };

        var attackersName = TeamName(_state.AttackersTeam, "assault-team-attackers");
        var defendersName = TeamName(_state.DefendersTeam, "assault-team-defenders");

        HudLabel.SetMarkup(
            $"{phase}\n" +
            Loc.GetString("assault-hud-tickets",
                ("attackersName", attackersName),
                ("defendersName", defendersName),
                ("attackers", _state.AttackersTickets),
                ("defenders", _state.DefendersTickets)) + "\n" +
            Loc.GetString("assault-hud-zone", ("zone", _state.CurrentZone), ("total", _state.TotalZones)) + "  " +
            Loc.GetString("assault-hud-round", ("time", FormatTime(_state.RoundEndsAt))) + "\n" +
            Loc.GetString("assault-hud-wave-attackers",
                ("name", attackersName),
                ("dead", _state.AttackersDead),
                ("total", _state.AttackersTotal)) + "  " +
            Loc.GetString("assault-hud-wave-defenders",
                ("name", defendersName),
                ("dead", _state.DefendersDead),
                ("total", _state.DefendersTotal)) + "\n" +
            Loc.GetString("assault-hud-capture", ("percent", (int) (_state.CaptureProgress * 100))) + "  " +
            Loc.GetString("assault-hud-wave-hint", ("percent", (int) (_state.WaveThreshold * 100))));
    }

    private string TeamName(string teamId, string fallback)
    {
        if (_proto.TryIndex<AssaultTeamPrototype>(teamId, out var proto) && !string.IsNullOrEmpty(proto.Name))
            return Loc.GetString(proto.Name);

        return Loc.GetString(fallback);
    }

    private string FormatTime(TimeSpan endsAt)
    {
        var remaining = endsAt - _timing.CurTime;
        if (remaining < TimeSpan.Zero)
            remaining = TimeSpan.Zero;

        return $"{(int) remaining.TotalMinutes}:{remaining.Seconds:D2}";
    }
}
