using Content.Client.UserInterface.Controls;
using Content.Shared._Grosse.Assault.UI;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Grosse.Assault.UI;

[GenerateTypedNameReferences]
public sealed partial class AssaultClassSelectMenu : FancyWindow
{
    public event Action<string>? ClassPicked;

    public AssaultClassSelectMenu()
    {
        RobustXamlLoader.Load(this);
    }

    public void Update(AssaultClassSelectEuiState state)
    {
        TicketsLabel.Text = Loc.GetString("assault-class-select-tickets", ("tickets", state.Tickets));
        ClassList.RemoveAllChildren();

        foreach (var cls in state.Classes)
        {
            var id = cls.Id;
            var button = new Button
            {
                Text = $"{cls.Name}  ({Loc.GetString("assault-lobby-cost", ("cost", cls.Cost))})",
                ToolTip = cls.Description,
                Disabled = !cls.Affordable || !cls.Available,
                ToggleMode = true,
                Pressed = state.SelectedClass == id,
                HorizontalExpand = true,
            };
            if (!cls.Available)
                button.ToolTip = Loc.GetString("assault-lobby-class-full");
            button.OnPressed += _ => ClassPicked?.Invoke(id);
            ClassList.AddChild(button);
        }
    }
}
