using Content.Shared._Grosse.Assault;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Grosse.Assault.UI;

[GenerateTypedNameReferences]
public sealed partial class AssaultLoadoutPanel : Control
{
    [Dependency] private IPrototypeManager _proto = default!;

    public event Action<bool, AssaultTeam?, string?>? LoadoutSelected;

    private AssaultTeam? _team;
    private string? _classId;
    private bool _random;
    private Dictionary<string, int> _classCounts = new();

    public AssaultLoadoutPanel()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        AttackersButton.OnPressed += _ => SelectTeam(AssaultTeam.Attackers);
        DefendersButton.OnPressed += _ => SelectTeam(AssaultTeam.Defenders);
        RandomButton.OnPressed += _ => SelectRandom();
    }

    public void SetVisibleEnabled(bool enabled)
    {
        Contents.Visible = enabled;
        Visible = enabled;
    }

    public void UpdateState(AssaultLobbyStateEvent state)
    {
        SetVisibleEnabled(state.Enabled);
        if (!state.Enabled)
            return;

        TeamCounts.Text = Loc.GetString("assault-team-counts",
            ("attackers", state.AttackersCount),
            ("defenders", state.DefendersCount));

        _random = state.RandomSelected;
        _team = state.SelectedTeam;
        _classId = state.SelectedClass;
        _classCounts = new Dictionary<string, int>(state.ClassCounts);

        AttackersButton.Pressed = !_random && _team == AssaultTeam.Attackers;
        DefendersButton.Pressed = !_random && _team == AssaultTeam.Defenders;
        RandomButton.Pressed = _random;

        StatusLabel.Text = _random
            ? Loc.GetString("assault-lobby-selected-random")
            : state.CanReady
                ? string.Empty
                : Loc.GetString("assault-lobby-ready-hint");

        RebuildClasses();
    }

    private void SelectTeam(AssaultTeam team)
    {
        _random = false;
        _team = team;
        _classId = null;
        RebuildClasses();
        LoadoutSelected?.Invoke(false, team, null);
    }

    private void SelectRandom()
    {
        _random = true;
        _team = null;
        _classId = null;
        RebuildClasses();
        LoadoutSelected?.Invoke(true, null, null);
    }

    private void SelectClass(string id)
    {
        if (_team == null)
            return;

        _random = false;
        _classId = id;
        LoadoutSelected?.Invoke(false, _team, id);
    }

    private void RebuildClasses()
    {
        ClassList.RemoveAllChildren();
        if (_random || _team == null)
            return;

        foreach (var proto in _proto.EnumeratePrototypes<AssaultClassPrototype>())
        {
            if (proto.Team != _team)
                continue;

            var id = proto.ID;
            var available = IsClassAvailable(id, proto.MaxCount);
            var button = new Button
            {
                Text = $"{Loc.GetString(proto.Name)}  ({Loc.GetString("assault-lobby-cost", ("cost", proto.Cost))})",
                ToolTip = available
                    ? Loc.GetString(proto.Description)
                    : Loc.GetString("assault-lobby-class-full"),
                ToggleMode = true,
                Pressed = _classId == id,
                Disabled = !available,
                HorizontalExpand = true,
            };
            button.OnPressed += _ => SelectClass(id);
            ClassList.AddChild(button);
        }
    }

    private bool IsClassAvailable(string id, int maxCount)
    {
        if (maxCount <= 0)
            return true;

        if (_classId == id)
            return true;

        return _classCounts.GetValueOrDefault(id) < maxCount;
    }
}
