using Content.Client.Message;
using Content.Shared._Grosse.Control;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;

namespace Content.Client._Grosse.Control.UI;

[GenerateTypedNameReferences]
public sealed partial class ControlHudControl : PanelContainer
{
    [Dependency] private IGameTiming _timing = default!;
    [Dependency] private IPrototypeManager _proto = default!;

    private ControlHudUpdateEvent? _state;

    public ControlHudControl()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        MouseFilter = MouseFilterMode.Ignore;
    }

    public void Update(ControlHudUpdateEvent state)
    {
        _state = state;
        Visible = state.Enabled;
        Refresh();
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        if (Visible)
            Refresh();
    }

    private void Refresh()
    {
        if (_state == null || !_state.Enabled)
        {
            Visible = false;
            return;
        }

        var phase = _state.Phase switch
        {
            ControlPhase.Prep => Loc.GetString("control-hud-phase-prep", ("time", FormatTime(_state.PhaseEndsAt))),
            ControlPhase.LastStand => Loc.GetString("control-hud-phase-laststand", ("time", FormatTime(_state.PhaseEndsAt))),
            ControlPhase.Ended => Loc.GetString("control-hud-phase-ended"),
            _ => Loc.GetString("control-hud-phase-fight"),
        };

        var teamAName = TeamName(_state.TeamAId, "control-team-a");
        var teamBName = TeamName(_state.TeamBId, "control-team-b");

        var points = string.Empty;
        foreach (var point in _state.Points)
        {
            var owner = point.Owner switch
            {
                ControlTeam.TeamA => teamAName,
                ControlTeam.TeamB => teamBName,
                _ => Loc.GetString("control-hud-point-neutral"),
            };
            points += Loc.GetString("control-hud-point", ("name", point.Name), ("owner", owner)) + "  ";
        }

        var lastStand = string.Empty;
        if (_state.Phase == ControlPhase.LastStand)
        {
            lastStand = "\n" + (_state.Winner == ControlTeam.TeamA
                ? Loc.GetString("control-hud-laststand-winners", ("name", teamAName))
                : Loc.GetString("control-hud-laststand-winners", ("name", teamBName)));
        }

        HudLabel.SetMarkup(
            $"{phase}\n" +
            Loc.GetString("control-hud-score",
                ("teamAName", teamAName),
                ("teamBName", teamBName),
                ("teamA", _state.TeamAScore),
                ("teamB", _state.TeamBScore),
                ("cap", _state.ScoreCap)) + "\n" +
            Loc.GetString("control-hud-round", ("time", FormatTime(_state.RoundEndsAt))) + "\n" +
            points.Trim() + "\n" +
            Loc.GetString("control-hud-wave-team-a",
                ("name", teamAName),
                ("dead", _state.TeamADead),
                ("total", _state.TeamATotal)) + "  " +
            Loc.GetString("control-hud-wave-team-b",
                ("name", teamBName),
                ("dead", _state.TeamBDead),
                ("total", _state.TeamBTotal)) +
            lastStand);
    }

    private string TeamName(string teamId, string fallback)
    {
        if (_proto.TryIndex<ControlTeamPrototype>(teamId, out var proto) && !string.IsNullOrEmpty(proto.Name))
            return Loc.GetString(proto.Name);

        return Loc.GetString(fallback);
    }

    private string FormatTime(TimeSpan endsAt)
    {
        var remaining = endsAt - _timing.CurTime;
        if (remaining < TimeSpan.Zero)
            remaining = TimeSpan.Zero;

        return $"{(int) remaining.TotalMinutes}:{remaining.Seconds:D2}";
    }
}
