using Content.Client.Message;
using Content.Shared._Grosse.Control;
using Content.Shared._Grosse.Pvp;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;

namespace Content.Client._Grosse.Control.UI;

[GenerateTypedNameReferences]
public sealed partial class ControlHudControl : PanelContainer
{
    [Dependency] private IGameTiming _timing = default!;
    [Dependency] private IPrototypeManager _proto = default!;

    private ControlHudUpdateEvent? _state;

    public ControlHudControl()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        MouseFilter = MouseFilterMode.Ignore;
    }

    public void Update(ControlHudUpdateEvent state)
    {
        _state = state;
        Visible = state.Enabled;
        Refresh();
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        if (Visible)
            Refresh();
    }

    private void Refresh()
    {
        if (_state == null || !_state.Enabled)
        {
            Visible = false;
            return;
        }

        var phase = _state.Phase switch
        {
            ControlPhase.Prep => Loc.GetString("control-hud-phase-prep", ("time", FormatTime(_state.PhaseEndsAt))),
            ControlPhase.LastStand => Loc.GetString("control-hud-phase-laststand", ("time", FormatTime(_state.PhaseEndsAt))),
            ControlPhase.Ended => Loc.GetString("control-hud-phase-ended"),
            _ => Loc.GetString("control-hud-phase-fight"),
        };

        var attackersName = TeamName(_state.AttackersTeam, "control-team-attackers");
        var defendersName = TeamName(_state.DefendersTeam, "control-team-defenders");

        var points = string.Empty;
        foreach (var point in _state.Points)
        {
            var owner = point.Owner switch
            {
                PvpTeam.Attackers => attackersName,
                PvpTeam.Defenders => defendersName,
                _ => Loc.GetString("control-hud-point-neutral"),
            };
            points += Loc.GetString("control-hud-point", ("name", point.Name), ("owner", owner)) + "  ";
        }

        var lastStand = string.Empty;
        if (_state.Phase == ControlPhase.LastStand)
        {
            lastStand = "\n" + (_state.Winner == PvpTeam.Attackers
                ? Loc.GetString("control-hud-laststand-winners", ("name", attackersName))
                : Loc.GetString("control-hud-laststand-winners", ("name", defendersName)));
        }

        HudLabel.SetMarkup(
            $"{phase}\n" +
            Loc.GetString("control-hud-score",
                ("attackersName", attackersName),
                ("defendersName", defendersName),
                ("attackers", _state.AttackersScore),
                ("defenders", _state.DefendersScore),
                ("cap", _state.ScoreCap)) + "\n" +
            Loc.GetString("control-hud-round", ("time", FormatTime(_state.RoundEndsAt))) + "\n" +
            points.Trim() + "\n" +
            Loc.GetString("control-hud-wave-attackers",
                ("name", attackersName),
                ("dead", _state.AttackersDead),
                ("total", _state.AttackersTotal)) + "  " +
            Loc.GetString("control-hud-wave-defenders",
                ("name", defendersName),
                ("dead", _state.DefendersDead),
                ("total", _state.DefendersTotal)) +
            lastStand);
    }

    private string TeamName(string teamId, string fallback)
    {
        if (_proto.TryIndex<ControlTeamPrototype>(teamId, out var proto) && !string.IsNullOrEmpty(proto.Name))
            return Loc.GetString(proto.Name);

        return Loc.GetString(fallback);
    }

    private string FormatTime(TimeSpan endsAt)
    {
        var remaining = endsAt - _timing.CurTime;
        if (remaining < TimeSpan.Zero)
            remaining = TimeSpan.Zero;

        return $"{(int) remaining.TotalMinutes}:{remaining.Seconds:D2}";
    }
}
