- type: entity
  name: Базированная База НПЦ
  id: MobBaseNpc
  parent:
  - BaseSimpleMob
  - MobCombat
  - StripableInventoryBase
  - MobPolymorphable
  description: Just a body, be calm.
  abstract: true
  components:
  - type: NameIdentifier
    group: GenericNumber
  - type: CombatMode
  - type: Stripping
  - type: Strippable
  - type: UserInterface
    interfaces:
      enum.StrippingUiKey.Key:
        type: StrippableBoundUserInterface
  - type: ComplexInteraction
  - type: StatusEffects
    allowed:
    - Stutter
  - type: HealthExaminable
    examinableTypes:
    - Blunt
    - Slash
    - Piercing
    - Heat
    - Shock
    - Cold
    - Caustic
    - Asphyxiation
    - Radiation
  - type: DamageOnHighSpeedImpact
    damage:
      types:
        Blunt: 5
    soundHit:
      path: /Audio/Effects/hit_kick.ogg
  - type: Pullable
  - type: LightningTarget
    priority: 2
    lightningExplode: false
  - type: ZombieImmune
  - type: Rotatable
  - type: InputMover
  - type: MobMover
  - type: Body
  - type: Climbing
  - type: MeleeWeapon
    angle: 0
    animation: WeaponArcFist
    soundHit:
        collection: Punch
    damage:
        types:
          Blunt: 5
  - type: NPCRetaliation
    attackMemoryLength: 10
  - type: NpcFactionMember
    factions:
      - SimpleNeutral
  - type: Inventory
  - type: Hands
  - type: RotationVisuals
    defaultRotation: 90
    horizontalRotation: 90
  - type: Fixtures
    fixtures:
      fix1:
        shape:
          !type:PhysShapeCircle
          radius: 0.35
        density: 300
        mask:
        - MobMask
        layer:
        - MobLayer
  - type: MobState
    allowedStates:
    - Alive
    - Dead
  - type: MobThresholds
    thresholds:
      0: Alive
      100: Dead
  - type: SlowOnDamage
    speedModifierThresholds:
      50: 0.5
  - type: Destructible
    thresholds:
    - trigger:
        !type:DamageTrigger
        damage: 400
      behaviors:
      - !type:DoActsBehavior
        acts: ["Destruction"]
      - !type:ExplodeBehavior
  - type: Injurable
    damageContainer: Biological
  - type: Puller
  - type: Tag
    tags:
      - CannotSuicide
      - DoorBumpOpener
      - FootstepSound

- type: entity
  abstract: true
  name: ксено
  id: BaseMobAntlion
  parent: MobXeno
  description: Угроза любой органической форме жизни
  suffix: Antlion
  components:
  - type: GhostRole
    prob: 0
  - type: NameIdentifier
    group: null
  - type: HTN
    rootTask:
      task: AntlionCompound
    blackboard:
      VisionRadius: !type:Single
        86
      AggroVisionRadius: !type:Single
        80
      NavClimb: !type:Bool
        true
      NavInteract: !type:Bool
        true
      NavPry: !type:Bool
        true
      NavSmash: !type:Bool
        true
  - type: Clickable
  - type: InteractionOutline
  - type: SolutionContainerManager
  - type: AtmosExposed
  - type: MobThresholds
    thresholds:
      0: Alive
      50: Critical
      300: Dead
  - type: Internals
  - type: Damageable
    damageModifierSet: Antlion
  - type: Injurable
    damageContainer: Biological
  - type: Body
  - type: Metabolizer
    solutionOnBody: false
    updateInterval: 0.25
    metabolizerTypes: [ Bloodsucker ]
    stages: [ Digestion, Bloodstream, Metabolites ]
  - type: Actions
  - type: DoAfter
  - type: Polymorphable
  - type: Buckle
  - type: Hands
    showInHands: false
  - type: MobState
    allowedStates:
      - Alive
      - Dead
  - type: MovementSpeedModifier
    baseWalkSpeed : 2.5
    baseSprintSpeed : 4
  - type: Stamina
    baseCritThreshold: 500
  - type: Appearance
  - type: Bloodstream
    bloodReferenceSolution:
      reagents:
      - ReagentId: Blood
        Quantity: 50
  - type: Puller
    needsHands: false
  - type: NoSlip
  - type: IgnoreSpiderWeb
  - type: IntrinsicRadioReceiver
  - type: ActiveRadio 
    channels:
    - Hivemind
  - type: IntrinsicRadioTransmitter
    channels:
    - Hivemind
  - type: NPCImprintingOnSpawnBehaviour
    spawnFriendsSearchRadius: 10
    whitelist:
      tags:
      - AntlionFollower
  - type: ZombieImmune
  - type: TTS
    voice: Sylvanas
#  - type: LanguageSpeaker
#    currentLanguage: Xeno
#  - type: LanguageKnowledge
#    speaks:
#    - Xeno
#    understands:
#    - Xeno
#  - type: NightVision
#    animation: true
#    transitionSpeed: 100
#    color: "#80008011"
  - type: TriggerOnMobstateChange
    mobState:
    - Dead
  - type: EmitSoundOnTrigger
    sound:
      collection: AntlionDeath
      params:
        volume: 1

- type: entity
  id: MobBaseNpcDungeon
  parent:
  - MobBaseNpcSalvage
  categories: [ HideSpawnMenu ]
  components:
  - type: MeleeWeapon
    range: 1.5
  - type: Fixtures
    fixtures:
      fix1:
        shape:
          !type:PhysShapeCircle
          radius: 0.35
        density: 300
        mask:
        - Impassable
        - HighImpassable
        - MidImpassable
        #- BlobImpassable
        layer:
        - MobLayer
      fix2:
        shape:
          !type:PhysShapeCircle
          radius: 1
        hard: false
        mask:
        - HighImpassable
        layer:
        - MobLayer
