using Content.Client.Info;
using Content.Client.Resources;
using Content.Client.Stylesheets;
using Content.Corvax.Interfaces.Client;
using Content.Shared.CCVar;
using Content.Shared.Preferences;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Maths;
using Robust.Shared.Player;
using Robust.Shared.Prototypes;

namespace Content.Client.Lobby.UI
{
    /// <summary>
    /// Holds the entire character setup GUI, from character picks to individual character editing.
    /// </summary>
    [GenerateTypedNameReferences]
    public sealed partial class CharacterSetupGui : Control
    {
        [Dependency] private IClientPreferencesManager _preferencesManager = default!;
        [Dependency] private IPrototypeManager _protomanager = default!;
        [Dependency] private IResourceCache _resourceCache = default!;
        [Dependency] private IConfigurationManager _cfg = default!;
        [Dependency] private ISharedPlayerManager _playerManager = default!;

        private readonly Button _createNewCharacterButton;

        public event Action<int>? SelectCharacter;
        public event Action<int>? DeleteCharacter;

        public CharacterSetupGui(HumanoidProfileEditor profileEditor)
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);

            // Flat rounded backing instead of the old near-black beveled button texture.
            BackgroundPanel.PanelOverride = new RoundedStyleBox
            {
                BackgroundColor = Color.FromHex("#262B35").WithAlpha(0.96f),
                BorderColor = Color.FromHex("#4C5665"),
                BorderThickness = 1f,
                CornerRadius = 12f,
                Padding = new Thickness(10f),
            };

            _createNewCharacterButton = new Button
            {
                Text = Loc.GetString("character-setup-gui-create-new-character-button"),
            };

            _createNewCharacterButton.OnPressed += args =>
            {
                _preferencesManager.CreateCharacter(HumanoidCharacterProfile.Random());
                ReloadCharacterPickers();
                args.Event.Handle();
            };

            CharEditor.AddChild(profileEditor);
            RulesButton.OnPressed += _ => new RulesAndInfoWindow().Open();

            _cfg.OnValueChanged(CCVars.SeeOwnNotes, p => AdminRemarksButton.Visible = p, true);
            // Corvax-Sponsors-Start
            if (IoCManager.Instance!.TryResolveType<ISponsorWindowCreator>(out var creator))
            {
                SponsorButton.Visible = true;
                SponsorButton.OnPressed += _ => creator.OpenWindow();
            }
            // Corvax-Sponsors-End
        }

        /// <summary>
        /// Disposes and reloads all character picker buttons from the preferences data.
        /// </summary>
        public void ReloadCharacterPickers()
        {
            _createNewCharacterButton.Orphan();
            Characters.RemoveAllChildren();

            var numberOfFullSlots = 0;
            var characterButtonsGroup = new ButtonGroup();

            if (!_preferencesManager.ServerDataLoaded)
            {
                return;
            }

            _createNewCharacterButton.ToolTip =
                Loc.GetString("character-setup-gui-create-new-character-button-tooltip",
                    ("maxCharacters", _preferencesManager.Settings!.MaxCharacterSlots));

            var selectedSlot = _preferencesManager.Preferences?.SelectedCharacterIndex;

            foreach (var (slot, character) in _preferencesManager.Preferences!.Characters)
            {
                numberOfFullSlots++;
                var characterPickerButton = new CharacterPickerButton(_protomanager,
                    _playerManager,
                    characterButtonsGroup,
                    character,
                    slot == selectedSlot);

                Characters.AddChild(characterPickerButton);

                characterPickerButton.OnPressed += args =>
                {
                    SelectCharacter?.Invoke(slot);
                };

                characterPickerButton.OnDeletePressed += () =>
                {
                    DeleteCharacter?.Invoke(slot);
                };
            }

            _createNewCharacterButton.Disabled = numberOfFullSlots >= _preferencesManager.Settings.MaxCharacterSlots;
            Characters.AddChild(_createNewCharacterButton);
        }
    }
}
